### ISSUE TITLE
Obtain SOC/battery charge level without (Manually) powering down

### ISSUE THREAD

**Issue by NiallDarwin** [samsta/BatteryController#10]
Title explains this issue. I'm just putting notes here as I research.

Message 5BC apparently contains GIDS.
'EV Can' sheet of this Googledoc here:

https://docs.google.com/spreadsheets/d/1EHa4R85BttuY4JZ-EnssH4YZddpsDVu6rUFm0P7ouwg/edit#gid=0

& in DBC format here:
https://github.com/dalathegreat/leaf_can_bus_messages/blob/master/EV-can_AZE0.dbc

**Comment by NiallDarwin** [comment]
@JimsterCoder has done a lot on this but it seems maybe we still don't have it long-term. If the code can control powering up and down the LBC we can do two things:
#1 Carefully control what startup messages go to the LBC relative to when it's powered on.
#2 If #1 fails (after a minute or a year) brute force getting accurate SOC by automatically power-cycling the lbc.
@JimsterCoder, keen to press on with this?

**Comment by JimsterCoder** [comment]
>  @JimsterCoder, keen to press on with this?

Yes, of course.

**Comment by NiallDarwin** [comment]
Cool, thanks

**Comment by NiallDarwin** [comment]
After some significant uptime the code seems to be achieving this goal. It seems either to start happy and remain that way or to very quickly fail. Issue 13 may help us with proving this out.

**Comment by NiallDarwin** [comment]
Revisiting this after a few months I'm frustrated that I haven't explained what we did to make it work**. I recall using information from this website* about controlling a Leaf Inverter:
http://productions.8dromeda.net/c55-leaf-inverter-protocol.html

From it I *definitely* added a dumb 50B message at 100ms as per his findings
I did not add 1D4 as it is related to torque
I *might* have added 11A at 10ms

So we need again to test which of these affect battery behaviour.

*Also known as celeron55 on mynissanleaf.com https://mynissanleaf.com/viewtopic.php?t=25027&start=10
**Note to self & James: Better documentation!

**Comment by NiallDarwin** [comment]
Figure out what the minimal is that we need to send the battery to keep it happy.
#1 Display fault code on console (1DB LB_Failsafe_Status: Caution Lamp Request ). Test.
#2 Try to cause fault; Stop transmitting anything.
#3 Try to remove fault; Add messages back, starting with 50B then 11A. If these don't fix it choose at random

**Comment by JimsterCoder** [comment]
#1 complete. BC running and showing 0 for Failsafe status
#2 progrees:
1 Set rates within happypoller.cpp of 1d4, 1f2, 11a to 100ms. Battery happy for at least 10 mins.
2Removed 50b & 50c. Changed happypoller to 1000000ms (1000s James). Seemed happy for over 10 minutes.
Idea: If the LBC gets the messages it wants when first powered up does it then not care that it stops receiving them? We haven't powered off the LBC for at least 24 hours.
3 As 2 but power cycle lbc. 
***Power on process: 1/ start battery controller. 2/ connect lbc to power
Yes, battery upset now.
4 Add in 50b & 50c, leave happypoller at huge time.  use power on process as above. Battery Happy
5 Remove 50c, only 50b being sent. battery happy.
6 only send 50c. Battery unhappy
***Conclusion seems to be only 50b required
7 removed 1d4, 1f2, 11a & 50c. Only 50b being sent. Powered up and will leave running for extended period to test theory.

**Comment by JimsterCoder** [comment]
7 followup. Niall says battery is still happy several days later.

8 to reduce bandwidth further I propose only sending a 50b reply to every 10x 55b received, this would drop the reply rate from 100ms to 1000ms.

**Comment by JimsterCoder** [comment]
FOR THE RECORD. After battery has gone to 'unhappy' mode (Failsafe is 4=Caution Lamp Request), it will not go to Failsafe=0 without being rebooted (according to the Chief Chimp).  To wit, the BC was not running for several days, after starting it, Failsafe was stuck at 4.  After rebooting LBC, Failsafe is 0 and has stayed there.

**Comment by JimsterCoder** [comment]
This issue has been solved by adding back in some messages which had been removed as they were thought unnecessary. See Sept 1, 2023 "WIP add back messages to battery"  This fixed the SOC problem, it now updates as it should.

**Comment by NiallDarwin** [comment]
Well done :)

>  Sept 1, 2023 "WIP add back messages to battery"
Is this the name and date of a commit?

**Comment by JimsterCoder** [comment]
Yes.
